#!/bin/bash

mkdir -p out
mkdir -p out/LTU-Report-Theme

cd src
pdflatex -output-directory=../out report.tex

cd ..
cp src/*.bib out/

cd out
bibtex report

for instance in bu*.aux; do # Whitespace-safe but not recursive.
	bibtex ${instance%.*}
done

cd ../src

pdflatex -output-directory=../out report.tex
pdflatex -output-directory=../out report.tex

